apiVersion: v1
kind: Service
metadata:
  name: #name
  namespace: easykube
spec:
  type: NodePort
  selector:
    app: nginx
    type: front-end
  ports:
    - port: 80
      targetPort: 80
      nodePort: #nodeport
